name: Python CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
      - name: Run tests
        run: python -m unittest discover -s tests
      - name: Run type checking
        run: pytype src scripts tests
      - name: Run style checks
        run: pycodestyle --exclude '.git,.venv,venv,archive,.idea' --ignore E121,E123,E126,E226,E24,E501,E704,W503,W504,W391,W292 src scripts tests

